<?php

namespace App;

use App\Events\ProjectCreated;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Mail;

class Project extends Model
{
//    protected $fillable = ['title', 'description'];
    protected $guarded = [];

    protected $dispatchesEvents = [
        'created' => ProjectCreated::class
    ];

//    protected static function boot()
//    {
//        parent::boot(); // TODO: Change the autogenerated stub
//        static::created(function ($project) {
//
//        });
//    }

    public function tasks() {
        return $this->hasMany(Task::class);
    }

    public function addTask($task) {
        $this->tasks()->create($task);
//        return Task::create([
//            'project_id' => $this->id,
//            'description' => $description
//        ]);
    }

    public function owner() {
        return $this->belongsTo(User::class);
    }
}
